name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autobuild
          pip install -e .

      - name: Generate API docs dynamically
        run: |
              find . -type f -name "__init__.py" -print0 | while IFS= read -r -d '' f; do
                  sphinx-apidoc -o docs/ "$(dirname "$f")"
              done
              sphinx-build -b html docs/ docs/_build/html
  
  deploy:
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_dir: docs/_build/html
            github_token: ${{ secrets.GITHUB_TOKEN }}
